# Generated by Django 5.0.2 on 2024-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_fa',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم نمایشی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم نمایشی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
