# Generated by Django 4.2 on 2024-07-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی یکتا')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('member_limit', models.PositiveIntegerField(default=False, verbose_name='محدودیت اعضا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('group_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='آیدی گروه')),
                ('type', models.PositiveSmallIntegerField(choices=[('خصوصی', 1), ('عمومی', 2)], default=1, verbose_name='نوع گروه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='group/image/', verbose_name='تصویر')),
                ('ban_list', models.ManyToManyField(blank=True, related_name='group_ban_list', to=settings.AUTH_USER_MODEL, verbose_name='لیست مسدودها')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='گروه')),
                ('link', models.ManyToManyField(blank=True, to='chat.link', verbose_name='لینک ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.role', verbose_name='سطح دسترسی')),
            ],
            options={
                'verbose_name': 'عضو گروه',
                'verbose_name_plural': 'اعضای گروه ها',
            },
        ),
    ]
