# Generated by Django 4.2 on 2024-07-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_groupmember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='گروه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(default=1, max_length=255, verbose_name='لینک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خصوصی'), (2, 'عمومی')], default=1, verbose_name='نوع گروه'),
        ),
    ]
