# Generated by Django 4.2 on 2024-07-10 11:56

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_link_group_link_link_link_user_alter_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='گروه'),
        ),
    ]
