# Generated by Django 4.2 on 2024-07-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_link_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmember', to='chat.group', verbose_name='گروه'),
        ),
    ]
