# Generated by Django 4.2 on 2024-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0008_link_expired_link_joined_member_link_member_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام نقش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='مجوزها'),
        ),
    ]
