# Generated by Django 4.2 on 2024-07-11 10:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_role_options_role_name_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام نقش'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('test 1', 1), ('test 2', 2), ('test 3', 3), ('test 4', 4), ('test 5', 5)], max_length=34, null=True, verbose_name='مجوزها'),
        ),
    ]
