# Generated by Django 4.2 on 2024-07-13 05:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_role_name_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='user_role',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='admin_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('add-user', 'Add User'), ('change-group-info', 'Change Group Info'), ('delete-messages', 'Delete Messages'), ('ban-users', 'Ban Users'), ('invite-users', 'Inviite Users Via Link'), ('pin-messages', 'Pin Messsges'), ('remain-anonymous', 'Remain Anonymous'), ('add-admin', 'Add New Admin')], max_length=105, null=True, verbose_name='مجوزها'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user_limited',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('send-messages', 'Send Messages'), ('add-member', 'Add Member'), ('user-pin-messages', 'Pin Messages'), ('change-group-info', 'Change Group Info')], max_length=60, null=True, verbose_name='محدودیت ها'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
