# Generated by Django 4.2 on 2024-07-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=255, verbose_name='نام وبسایت')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('about', models.TextField(blank=True, null=True, verbose_name='توضیحات فوتر')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون')),
                ('main_banner', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='بنر اصلی')),
                ('main_banner_link', models.CharField(blank=True, help_text='سایز پیشنهادی برای ارتفاع بنر حداکثر ۲۵۰ و طول آن حداکثر ۱۴۴۰ می باشد.', max_length=255, null=True, verbose_name='لینک بنر اصلی')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('video', models.FileField(blank=True, null=True, upload_to='site/', verbose_name='فیلم معرفی')),
            ],
            options={
                'verbose_name': 'پیکربندی سایت',
                'verbose_name_plural': 'پیکربندی سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('icon', models.FileField(upload_to='socials/logo/%y/%m/%d', verbose_name='آیکون')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('phone', models.CharField(max_length=255, verbose_name='شماره تلفن')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'شماره تلفن',
                'verbose_name_plural': 'شماره تلفن ها',
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='home_slider/', verbose_name='تصویر')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات کاری')),
                ('map', models.TextField(blank=True, help_text='کد html نقشه را وارد کنید', null=True, verbose_name='نقشه')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
