# Generated by Django 5.0.2 on 2024-02-13 07:36

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=255, verbose_name='نام وبسایت')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='نام وبسایت')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='نام وبسایت')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('slogan_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('copyright_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('copyright_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون')),
                ('main_banner', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='بنر اصلی')),
                ('main_banner_en', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='بنر اصلی')),
                ('main_banner_fa', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='بنر اصلی')),
                ('main_banner_link', models.CharField(blank=True, help_text='سایز پیشنهادی برای ارتفاع بنر حداکثر ۲۵۰ و طول آن حداکثر ۱۴۴۰ می باشد.', max_length=255, null=True, verbose_name='لینک بنر اصلی')),
                ('main_banner_link_en', models.CharField(blank=True, help_text='سایز پیشنهادی برای ارتفاع بنر حداکثر ۲۵۰ و طول آن حداکثر ۱۴۴۰ می باشد.', max_length=255, null=True, verbose_name='لینک بنر اصلی')),
                ('main_banner_link_fa', models.CharField(blank=True, help_text='سایز پیشنهادی برای ارتفاع بنر حداکثر ۲۵۰ و طول آن حداکثر ۱۴۴۰ می باشد.', max_length=255, null=True, verbose_name='لینک بنر اصلی')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_fa', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('map', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
            ],
            options={
                'verbose_name': 'پیکربندی سایت',
                'verbose_name_plural': 'پیکربندی سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('username_or_id', models.CharField(help_text='مثال: firefly@', max_length=100, verbose_name='نام کاربری یا آیدی')),
                ('icon', models.CharField(blank=True, help_text='به صورت پیشفرض از fontawesome پشتیبانی می شود، فقط کافیست نام آیکون را وارد کنید. برای مثال: facebook', max_length=100, null=True, verbose_name='آیکون')),
                ('icon_background_color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ پس زمینه آیکون')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('phone', models.CharField(max_length=255, verbose_name='شماره تلفن')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'شماره تلفن',
                'verbose_name_plural': 'شماره تلفن ها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
