# Generated by Django 5.0.2 on 2024-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteglobalsetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteglobalsetting',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='siteglobalsetting',
            name='address_fa',
        ),
        migrations.AddField(
            model_name='siteglobalsetting',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره سایت'),
        ),
    ]
