# Generated by Django 5.0.2 on 2024-02-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_siteglobalsetting_about_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='address',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن'),
        ),
    ]
