# Generated by Django 5.0.2 on 2024-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_address_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map',
            field=models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه'),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
