# Generated by Django 5.0.2 on 2024-03-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_remove_siteglobalsetting_map_alter_address_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('logo', models.ImageField(upload_to='home_slider/', verbose_name='تصویر')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.siteglobalsetting', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدر صفحه اصلی',
            },
        ),
    ]
