# Generated by Django 5.0.2 on 2024-03-14 09:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_homepageslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageslider',
            old_name='logo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='icon_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None, verbose_name='رنگ پس زمینه آیکون'),
        ),
    ]
