# Generated by Django 5.0.2 on 2024-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_rename_logo_homepageslider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasetting',
            name='icon_background_color',
        ),
        migrations.RemoveField(
            model_name='socialmediasetting',
            name='username_or_id',
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='icon',
            field=models.FileField(default=2, upload_to='socials/logo/%y/%m/%d', verbose_name='آیکون'),
            preserve_default=False,
        ),
    ]
